// for BurgerBuilder.js
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
// for Order.js
export const SEND_ORDER_SUCCEEDED = 'SEND_ORDER_SUCCEEDED';
export const SEND_ORDER_FAILED = 'SEND_ORDER_FAILED';
