export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const SEND_ORDER_SUCCEEDED = 'SEND_ORDER_SUCCEEDED';
export const SEND_ORDER_FAILED = 'SEND_ORDER_FAILED';
export const INIT_FETCH_ORDER = 'INIT_FETCH_ORDER';
export const FETCH_ORDER_SUCCEEDED = 'FETCH_ORDER_SUCCEEDED';
export const FETCH_ORDER_FAILED = 'FETCH_ORDER_FAILED';

export const SHOW_LOADING = 'SHOW_LOADING';

export const INIT_PURCHASE = 'INIT_PURCHASE';

export const START_AUTH = 'START_AUTH';
export const INIT_AUTH = 'INIT_AUTH';
export const AUTH_SUCCEEDED = 'AUTH_SUCCEEDED';
export const AUTH_FAILED = 'AUTH_FAILED';
export const START_CHECK_AUTH_LOGIN = 'START_CHECK_AUTH_LOGIN';
export const INIT_CHECK_AUTH_LOGOUT = 'INIT_CHECK_AUTH_LOGOUT';
export const INIT_AUTH_LOGOUT = 'INIT_AUTH_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_DIRECTED_PATH = 'SET_DIRECTED_PATH';
